# Generated by Django 5.2.17 on 2026-09-28 12:05

import apps.educandos.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('identificacao', models.CharField(help_text='Identificação interna, sem utilizar dados pessoais desnecessários.', max_length=120, unique=True, verbose_name='identificação do núcleo')),
                ('endereco', models.TextField(verbose_name='endereço')),
                ('composicao_familiar', models.TextField(help_text='Descreva resumidamente os membros que compõem o núcleo.', verbose_name='composição familiar')),
            ],
            options={
                'verbose_name': 'núcleo familiar',
                'verbose_name_plural': 'núcleos familiares',
                'ordering': ['identificacao'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[apps.educandos.validators.validar_cpf], verbose_name='CPF')),
                ('contato', models.CharField(help_text='Telefone com DDD.', max_length=20, validators=[apps.educandos.validators.validar_contato])),
                ('parentesco', models.CharField(max_length=60)),
                ('nucleo_familiar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to='educandos.nucleofamiliar')),
            ],
            options={
                'verbose_name': 'responsável',
                'verbose_name_plural': 'responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Educando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=150, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[apps.educandos.validators.validar_cpf], verbose_name='CPF')),
                ('endereco', models.TextField(verbose_name='endereço')),
                ('contato', models.CharField(help_text='Telefone com DDD.', max_length=20, validators=[apps.educandos.validators.validar_contato])),
                ('nucleo_familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='educandos', to='educandos.nucleofamiliar')),
                ('responsavel_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='educandos_principais', to='educandos.responsavel')),
            ],
            options={
                'verbose_name': 'educando',
                'verbose_name_plural': 'educandos',
                'ordering': ['nome_completo'],
                'permissions': [('view_relatorio_desenvolvimento', 'Pode visualizar o relatório de desenvolvimento')],
            },
        ),
        migrations.CreateModel(
            name='SituacaoSocioassistencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_referencia', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de referência')),
                ('situacao_socioeconomica', models.TextField(help_text='Registre a situação observada no período.', verbose_name='situação socioeconômica')),
                ('beneficios_sociais', models.TextField(help_text='Informe os benefícios ou registre que não possui.', verbose_name='benefícios sociais')),
                ('vulnerabilidades_identificadas', models.TextField(help_text='Informe as vulnerabilidades ou registre que não foram identificadas.', verbose_name='vulnerabilidades identificadas')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('educando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacoes_socioassistenciais', to='educandos.educando')),
                ('registrado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situacoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'situação socioassistencial',
                'verbose_name_plural': 'situações socioassistenciais',
                'ordering': ['-data_referencia', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoEducandoResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_vinculo', models.CharField(choices=[('RESPONSAVEL_LEGAL', 'Responsável legal'), ('FAMILIAR', 'Familiar'), ('OUTRO', 'Outro responsável')], default='RESPONSAVEL_LEGAL', max_length=30)),
                ('principal', models.BooleanField(default=False, help_text='Marque quando este for o responsável principal do educando.')),
                ('educando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_responsaveis', to='educandos.educando')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_educandos', to='educandos.responsavel')),
            ],
            options={
                'verbose_name': 'vínculo entre educando e responsável',
                'verbose_name_plural': 'vínculos entre educandos e responsáveis',
                'ordering': ['educando__nome_completo', 'responsavel__nome_completo'],
                'constraints': [models.UniqueConstraint(fields=('educando', 'responsavel'), name='uq_educando_responsavel'), models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('educando',), name='uq_responsavel_principal_por_educando')],
            },
        ),
    ]
